apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yelb-app-ci
  namespace: yelb
spec:
  params:
    - name: gitRepo
      type: string
      description: |
        Git repo containing the yelb go function.
  tasks:
    #
    # setup
    #
    - name: setup-git-clone
      params:
        - name: gitRepo
          value: "$(params.gitRepo)"
        - name: gitRepoDestination
          value: /workspace/code
      taskRef:
        kind: ClusterTask
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: workspace

    #
    # test
    #
    - name: test-lint-go
      params:
        - name: goTestDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - setup-git-clone
      taskRef:
        kind: ClusterTask
        name: test-lint-go
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-unit-go
      params:
        - name: goTestDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - test-lint-go
      taskRef:
        kind: ClusterTask
        name: test-unit-go
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-integration-yelb
      runAfter:
        - test-unit-go
      taskRef:
        kind: Task
        name: test-integration-yelb
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: yelb-app-ci
  namespace: yelb
spec:
  params:
    - name: gitRepo
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: yelb-app-ci-
        namespace: yelb
      spec:
        pipelineRef:
          name: yelp-app-ci
        params:
          - name: gitRepo
            value: "$(tt.params.gitRepo)"
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yelb-app-cd
  namespace: yelb
spec:
  params:
    - name: gitRepo
      type: string
      description: |
        Git repo containing the yelb go function.
  tasks:
    #
    # setup
    #
    - name: setup-knative
      params:
        - name: knativeBinaryLocation
          value: /tools/bin
        - name: knativeVersion
          value: v1.12.0
        - name: knativeFuncVersion
          value: v1.12.0
      taskRef:
        kind: ClusterTask
        name: setup-knative
      workspaces:
        - name: tools
          workspace: tools
    - name: setup-git-clone
      params:
        - name: gitRepo
          value: "$(params.gitRepo)"
        - name: gitRepoDestination
          value: /workspace/code
      taskRef:
        kind: ClusterTask
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: workspace

    #
    # deploy
    #
    - name: deploy-knative
      params:
        - name: knativeDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - setup-knative
        - setup-git-clone
      taskRef:
        kind: ClusterTask
        name: deploy-knative
      workspaces:
        - name: workspace
          workspace: workspace
        - name: tools
          workspace: tools
  workspaces:
    - name: workspace
    - name: tools
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: yelb-app-cd
  namespace: yelb
spec:
  params:
    - name: gitRepo
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: yelb-app-cd-
        namespace: yelb
      spec:
        pipelineRef:
          name: yelp-app-cd
        params:
          - name: gitRepo
            value: "$(tt.params.gitRepo)"
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          - name: tools
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yelb-ui-ci
  namespace: yelb
spec:
  tasks:
    #
    # setup
    #
    - name: setup-git-clone
      params:
        - name: gitRepo
          value: 'https://github.com/scottd018-demos/yelb.git'
        - name: gitRepoDestination
          value: /workspace/code
      taskRef:
        kind: ClusterTask
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
# ---
# apiVersion: tekton.dev/v1
# kind: Pipeline
# metadata:
#   name: yelb-ui-cd
#   namespace: yelb
# spec:
#   tasks:
#     #
#     # setup
#     #
#     - name: setup-git-clone
#       params:
#         - name: gitRepo
#           value: 'https://github.com/scottd018-demos/yelb.git'
#         - name: gitRepoDestination
#           value: /workspace/code
#       taskRef:
#         kind: ClusterTask
#         name: setup-git-clone
#       workspaces:
#         - name: workspace
#           workspace: workspace

#     #
#     # deploy
#     #
#     - name: deploy-s2i
#       params:
#         - name: knativeDirectory
#           value: /workspace/code/yelb-appserver/go
#       runAfter:
#         - setup-git-clone
#       taskRef:
#         kind: ClusterTask
#         name: deploy-knative
#       workspaces:
#         - name: workspace
#           workspace: workspace
#         - name: tools
#           workspace: tools
#   workspaces:
#     - name: workspace
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github
  namespace: yelb
spec:
  params:
    - name: gitRepo
      value: "$(body.repository.clone_url)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github
  namespace: yelb
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev/v1alpha1
          params:
            - name: eventTypes
              value:
                - push
      bindings:
        - ref: github
      template:
        ref: yelp-app-ci
    - name: github
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev/v1alpha1
          params:
            - name: eventTypes
              value:
                - release
      bindings:
        - ref: github
      template:
        ref: yelp-app-cd
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github
  name: github
  namespace: yelb
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-github