---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tools
  namespace: yelb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
  namespace: yelb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yelb-app
  namespace: yelb
spec:
  tasks:
    - name: setup-git-clone
      params:
        - name: gitRepo
          value: 'https://github.com/scottd018-demos/yelb.git'
        - name: gitRepoDestination
          value: /workspace/code
      taskRef:
        kind: ClusterTask
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-unit-go
      params:
        - name: goTestDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - setup-git-clone
        - setup-knative
      taskRef:
        kind: ClusterTask
        name: test-unit-go
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-integration-yelb
      runAfter:
        - test-unit-go
      taskRef:
        kind: Task
        name: test-integration-yelb
      workspaces:
        - name: workspace
          workspace: workspace
    - name: setup-knative
      params:
        - name: knativeBinaryLocation
          value: /tools/bin
        - name: knativeVersion
          value: v1.12.0
        - name: knativeFuncVersion
          value: v1.12.0
      taskRef:
        kind: ClusterTask
        name: setup-knative
      workspaces:
        - name: tools
          workspace: tools
    - name: deploy-knative
      params:
        - name: knativeDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - test-integration-yelb
      taskRef:
        kind: ClusterTask
        name: deploy-knative
      workspaces:
        - name: workspace
          workspace: workspace
        - name: tools
          workspace: tools
  workspaces:
    - name: workspace
    - name: tools
