apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yelb-app-ci
  namespace: yelb
spec:
  tasks:
    #
    # setup
    #
    - name: setup-git-clone
      params:
        - name: gitRepo
          value: 'https://github.com/scottd018-demos/yelb.git'
        - name: gitRepoDestination
          value: /workspace/code
      taskRef:
        kind: ClusterTask
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: workspace

    #
    # test
    #
    - name: test-lint-go
      params:
        - name: goTestDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - setup-git-clone
      taskRef:
        kind: ClusterTask
        name: test-lint-go
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-unit-go
      params:
        - name: goTestDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - test-lint-go
      taskRef:
        kind: ClusterTask
        name: test-unit-go
      workspaces:
        - name: workspace
          workspace: workspace
    - name: test-integration-yelb
      runAfter:
        - test-unit-go
      taskRef:
        kind: Task
        name: test-integration-yelb
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: yelb-app-cd
  namespace: yelb
spec:
  tasks:
    #
    # setup
    #
    - name: setup-knative
      params:
        - name: knativeBinaryLocation
          value: /tools/bin
        - name: knativeVersion
          value: v1.12.0
        - name: knativeFuncVersion
          value: v1.12.0
      taskRef:
        kind: ClusterTask
        name: setup-knative
      workspaces:
        - name: tools
          workspace: tools
    - name: setup-git-clone
      params:
        - name: gitRepo
          value: 'https://github.com/scottd018-demos/yelb.git'
        - name: gitRepoDestination
          value: /workspace/code
      taskRef:
        kind: ClusterTask
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: workspace

    #
    # deploy
    #
    - name: deploy-knative
      params:
        - name: knativeDirectory
          value: /workspace/code/yelb-appserver/go
      runAfter:
        - setup-knative
        - setup-git-clone
      taskRef:
        kind: ClusterTask
        name: deploy-knative
      workspaces:
        - name: workspace
          workspace: workspace
        - name: tools
          workspace: tools
  workspaces:
    - name: workspace
    - name: tools
