---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: setup-knative
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: knativeBinaryLocation
      type: string
      default: /tools/bin
      description: |
        Location where knative tooling is placed.  Should be located in the path.
    - name: knativeVersion
      type: string
      default: v1.12.0
      description: |
        The version of kn to install
    - name: knativeFuncVersion
      type: string
      default: v1.12.0
      description: |
        The version of the kn func plugin to install
  steps:
    - name: setup-install-knative-tools
      image: registry.access.redhat.com/ubi9/s2i-base:1-410.1674496682
      script: |
        #!/usr/bin/env bash
        set -e
        mkdir -p $(params.knativeBinaryLocation)
        wget https://github.com/knative/client/releases/download/knative-$(params.knativeVersion)/kn-linux-amd64 -O $(params.knativeBinaryLocation)/kn
        chmod +x $(params.knativeBinaryLocation)/kn
        wget https://github.com/knative/func/releases/download/knative-$(params.knativeFuncVersion)/func_linux_amd64 -O $(params.knativeBinaryLocation)/kn-func
        chmod +x $(params.knativeBinaryLocation)/kn-func
  stepTemplate:
    securityContext:
      runAsGroup: 0
  workspaces:
    - name: tools
      mountPath: /tools
