---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: test-unit-go
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: goTestDirectory
      type: string
      default: /workspace/code/demo-app
      description: |
        The folder to use for running the go test
  steps:
    - name: test-unit-go
      image: registry.access.redhat.com/ubi9/go-toolset:1.18.9-2.1674497385
      script: |
        #!/usr/bin/env bash
        set -e
        cd $(params.goTestDirectory)
        go test -tags=unit
  workspaces:
    - name: workspace
      mountPath: /workspace
