---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: deploy-knative
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: knativeDirectory
      type: string
      default: /workspace/code/demo-app
      description: |
        The folder which contains the knative function code and is used to 
        build the image.
  steps:
    - name: build-knative-image
      image: registry.access.redhat.com/ubi9/podman:9.1.0-12
      script: |
        #!/usr/bin/env bash
        set -e
        export PATH="${PATH}:/workspace/tools/bin"
        cd $(params.knativeDirectory)
        kn func build -v
    - name: deploy-knative
      image: registry.access.redhat.com/ubi9/podman:9.1.0-12
      script: |
        #!/usr/bin/env bash
        set -e
        export PATH="${PATH}:/workspace/tools/bin"
        cd $(params.knativeDirectory)
        kn func deploy --build=false -v
  stepTemplate:
    securityContext:
      runAsUser: 0
      privileged: true
  workspaces:
    - name: workspace
      mountPath: /workspace
