---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: deploy-knative
spec:
  params:
    - name: knativeDirectory
      type: string
      default: /workspace/code/demo-app
      description: |
        The folder which contains the knative function code and is used to 
        build the image.
  steps:
    - name: build-knative-image
      image: registry.access.redhat.com/ubi9/podman:9.1.0-12
      script: |
        #!/usr/bin/env bash
        set -e
        export PATH="${PATH}:/tools/bin"
        cd $(params.knativeDirectory)
        kn func build -v
    - name: deploy-knative
      image: registry.access.redhat.com/ubi9/podman:9.1.0-12
      script: |
        #!/usr/bin/env bash
        set -e
        export PATH="${PATH}:/tools/bin"
        cd $(params.knativeDirectory)
        # kn func deploy --build=false -v

        # if we have a secret, use it
        if [ -d /secret ]; then
          for SECRET in `find /secret -type f`; do
            KEY=`echo $SECRET | awk -F'/' '${print $NF}'`
            VALUE=`cat $SECRET`

            echo "${KEY}=${VALUE}"
          done
        fi
  stepTemplate:
    securityContext:
      runAsUser: 0
      privileged: true
  workspaces:
    - name: images
      mountPath: /var/lib/containers
    - name: workspace
      mountPath: /workspace
    - name: tools
      mountPath: /tools
    - name: secret
      mountPath: /secret
      optional: true
