---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: test-lint-go
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
    - name: goTestDirectory
      type: string
      default: /workspace/code/demo-app
      description: |
        The folder to use for running the go test
  steps:
    - name: test-lint-go
      image: golangci/golangci-lint:v1.55.2
      script: |
        #!/usr/bin/env bash
        set -e
        cd $(params.goTestDirectory)

        # print linters
        golangci-lint linters

        # run linter
        golangci-lint run
  workspaces:
    - name: workspace
      mountPath: /workspace
