---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: setup-git-clone
spec:
  params:
    - name: gitRepo
      type: string
      description: |
        The url of the public git repo to clone
    - name: gitRepoDestination
      type: string
      default: /workspace/code
      description: |
        The destination folder inside of the workspace where the repo is downloaded
  steps:
    - name: setup-git-clone
      image: registry.access.redhat.com/ubi9/s2i-base:1-410.1674496682
      script: |
        #!/usr/bin/env bash
        set -e

        # clone if the directory does not exist otherwise pull the latest changes
        if [ ! -d $(params.gitRepoDestination) ]; then
          git clone $(params.gitRepo) $(params.gitRepoDestination)
        else
          cd $(params.gitRepoDestination)
          git pull
        fi

        # print tree to debug
        find $(params.gitRepoDestination) -type f
  stepTemplate:
    securityContext:
      runAsGroup: 0
  workspaces:
    - name: workspace
      mountPath: /workspace