---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: deploy-knative
spec:
  params:
    - name: knativeDirectory
      type: string
      default: /workspace/code/demo-app
      description: |
        The folder which contains the knative function code and is used to 
        build the image.
  steps:
    - name: deploy-knative
      image: registry.access.redhat.com/ubi9/podman:9.1.0-12
      script: |
        #!/usr/bin/env bash
        set -e
        export PATH="${PATH}:/tools/bin"
        cd $(params.knativeDirectory)
        kn func deploy -v
  stepTemplate:
    securityContext:
      runAsUser: 0
      privileged: true
  workspaces:
    - name: workspace
      mountPath: /workspace
    - name: tools
      mountPath: /tools
